# Generated by Django 5.2.4 on 2025-07-15 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('LIVE', 'Live'), ('FINISHED', 'Finished')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_presentations', to='users.user')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speeches', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='PresentationAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presentations.presentation')),
            ],
            options={
                'unique_together': {('presentation', 'attendee')},
            },
        ),
    ]
