# Generated by Django 5.2.4 on 2025-07-15 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('presentations', '0001_initial'),
        ('quizzes', '0001_initial'),
        ('users', '0002_user_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SPEAKER', 'Speaker'), ('QUIZ', 'Quiz'), ('ENVIRONMENT', 'Environment')], max_length=20)),
                ('reason', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presentations.presentation')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
