# Generated by Django 5.2.4 on 2025-07-14 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('options', models.JSONField()),
                ('correct_answer', models.CharField(max_length=5)),
                ('explanation', models.TextField()),
                ('status', models.CharField(choices=[('READY', '准备中'), ('ACTIVE', '进行中'), ('CLOSED', '已关闭')], default='READY', max_length=10)),
                ('time_limit', models.PositiveIntegerField(default=30)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.presentation')),
            ],
        ),
    ]
