# Generated by Django 5.2.4 on 2025-07-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='materials/')),
                ('file_type', models.CharField(max_length=20)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
