# Generated by Django 5.2.4 on 2025-07-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_alter_uploadedmaterial_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedmaterial',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
    ]
