# Generated by Django 5.2.4 on 2025-07-14 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_uploadedmaterial_extracted_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
