# Generated by Django 5.2.4 on 2025-07-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quiz_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('upcoming', '未开始'), ('active', '进行中'), ('completed', '已结束')], default='upcoming', max_length=10),
        ),
    ]
