# Generated by Django 5.2.4 on 2025-07-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_alter_upload_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file_path',
            field=models.CharField(max_length=255),
        ),
    ]
