# Generated by Django 5.2.4 on 2025-07-16 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_upload_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtractedText',
        ),
    ]
