# Generated by Django 5.2.4 on 2025-07-14 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('show', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', '待审核'), ('APPROVED', '已通过'), ('REJECTED', '已拒绝')], default='APPROVED', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.presentation')),
            ],
            options={
                'unique_together': {('presentation', 'attendee')},
            },
        ),
    ]
